name: flight_erp
description: نظام إدارة وكالة السفر - Travel Agency ERP
publish_to: 'none'
version: 2.0.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  supabase_flutter: ^2.5.6
  go_router: ^14.2.7
  equatable: ^2.0.5
  uuid: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
